# Generated by Django 2.2.5 on 2020-08-03 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(blank=True, max_length=50, null=True, verbose_name='轮播图描述')),
                ('image', models.ImageField(upload_to='', verbose_name='轮播图片')),
                ('display', models.BooleanField(default=True, verbose_name='是否展示')),
                ('index', models.SmallIntegerField(default=0, verbose_name='优先级')),
            ],
            options={
                'verbose_name': '轮播图',
                'verbose_name_plural': '轮播图',
            },
        ),
        migrations.CreateModel(
            name='Cases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='标题')),
                ('content', models.CharField(max_length=255, verbose_name='内容')),
                ('image', models.ImageField(upload_to='', verbose_name='图片')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('type', models.SmallIntegerField(choices=[(0, '家装案例'), (1, '工装案例'), (2, '其他案例')], default=0, verbose_name='类型')),
                ('display', models.BooleanField(default=True, verbose_name='是否展示')),
            ],
            options={
                'verbose_name': '装修案例',
                'verbose_name_plural': '装修案例',
            },
        ),
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='', verbose_name='公司logo')),
                ('name', models.CharField(max_length=255, verbose_name='公司名称')),
                ('desc', models.TextField(verbose_name='公司简介')),
                ('short_desc', models.CharField(max_length=526, verbose_name='公司简介')),
                ('image', models.ImageField(upload_to='', verbose_name='公司照片')),
                ('location', models.CharField(default='', max_length=256, verbose_name='公司地址')),
                ('phone_num', models.CharField(default='', max_length=50, verbose_name='手机电话')),
                ('mobile', models.CharField(default='', max_length=11, verbose_name='座机号码')),
                ('email', models.EmailField(default='', max_length=254, verbose_name='邮件')),
                ('wechat', models.CharField(default='', max_length=255, verbose_name='微信')),
                ('display', models.BooleanField(default=False, verbose_name='是否为默认选项')),
            ],
            options={
                'verbose_name': '公司信息',
                'verbose_name_plural': '公司信息',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='标题')),
                ('content', models.CharField(max_length=255, verbose_name='内容')),
                ('image', models.ImageField(upload_to='', verbose_name='图片')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('type', models.SmallIntegerField(choices=[(0, '公司新闻'), (1, '行业新闻')], default=0, verbose_name='类型')),
                ('display', models.BooleanField(default=True, verbose_name='是否展示')),
            ],
            options={
                'verbose_name': '新闻',
                'verbose_name_plural': '新闻',
            },
        ),
        migrations.CreateModel(
            name='Recruitment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=56, verbose_name='标题')),
                ('content', models.CharField(max_length=255, verbose_name='内容')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('desc', models.CharField(max_length=256)),
                ('display', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': '招聘信息',
                'verbose_name_plural': '招聘信息',
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('desc', models.CharField(max_length=526)),
                ('avatar', models.ImageField(upload_to='')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('display', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': '员工信息',
                'verbose_name_plural': '员工信息',
            },
        ),
    ]
