# Generated by Django 2.2 on 2020-08-01 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='upload/')),
                ('display', models.BooleanField(default=True)),
                ('index', models.SmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='upload/')),
                ('name', models.CharField(max_length=255)),
                ('desc', models.TextField()),
                ('short_desc', models.CharField(max_length=526)),
                ('image', models.ImageField(upload_to='upload/')),
                ('location', models.CharField(default='', max_length=256)),
                ('phone_num', models.CharField(default='', max_length=50)),
                ('mobile', models.CharField(default='', max_length=11)),
                ('email', models.EmailField(default='', max_length=254)),
                ('wechat', models.CharField(default='', max_length=255)),
                ('display', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('content', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='upload/')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('display', models.BooleanField(default=True)),
            ],
        ),
    ]
