# Generated by Django 2.2 on 2020-08-01 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='type',
            field=models.SmallIntegerField(choices=[(0, '公司新闻'), (1, '行业新闻')], default=0),
        ),
    ]
