# Generated by Django 2.2.5 on 2020-08-03 13:01

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recruitment',
            name='desc',
        ),
        migrations.AlterField(
            model_name='cases',
            name='content',
            field=tinymce.models.HTMLField(verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='desc',
            field=tinymce.models.HTMLField(verbose_name='公司简介'),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='short_desc',
            field=tinymce.models.HTMLField(verbose_name='公司简介'),
        ),
        migrations.AlterField(
            model_name='news',
            name='content',
            field=tinymce.models.HTMLField(verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='recruitment',
            name='content',
            field=tinymce.models.HTMLField(verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='avatar',
            field=models.ImageField(upload_to='', verbose_name='头像'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='desc',
            field=tinymce.models.HTMLField(verbose_name='员工简介'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='name',
            field=models.CharField(max_length=10, verbose_name='员工姓名'),
        ),
    ]
