# Generated by Django 2.2 on 2020-08-01 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_news_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('content', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='upload/')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('type', models.SmallIntegerField(choices=[(0, '家装案例'), (1, '工装案例'), (2, '其他案例')], default=0)),
                ('display', models.BooleanField(default=True)),
            ],
        ),
    ]
