# Generated by Django 2.2 on 2020-08-02 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_staff'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={'verbose_name': '轮播图', 'verbose_name_plural': '轮播图'},
        ),
        migrations.AlterModelOptions(
            name='cases',
            options={'verbose_name': '装修案例', 'verbose_name_plural': '装修案例'},
        ),
        migrations.AlterModelOptions(
            name='companyinfo',
            options={'verbose_name': '公司信息', 'verbose_name_plural': '公司信息'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': '新闻', 'verbose_name_plural': '新闻'},
        ),
        migrations.AlterModelOptions(
            name='recruitment',
            options={'verbose_name': '招聘信息', 'verbose_name_plural': '招聘信息'},
        ),
        migrations.AlterModelOptions(
            name='staff',
            options={'verbose_name': '员工信息', 'verbose_name_plural': '员工信息'},
        ),
        migrations.AddField(
            model_name='banner',
            name='desc',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
